apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDTjCCAjagAwIBAgIUP/X5ZgyHJ/o/icFQfijJnlyVb88wDQYJKoZIhvcNAQEL
      BQAwPjEnMA8GA1UEChMIaGFuZ3pob3UwFAYDVQQKEw1hbGliYWJhIGNsb3VkMRMw
      EQYDVQQDEwprdWJlcm5ldGVzMCAXDTI0MDgxMDE2MzgwMFoYDzIwNTQwODAzMTYz
      ODAwWjA+MScwDwYDVQQKEwhoYW5nemhvdTAUBgNVBAoTDWFsaWJhYmEgY2xvdWQx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQDbevMLfFyqqsfA6TNVKabAd17nOLRJRJf32AyXURZS1CEmBAdQps7LSXkB
      kvrqbHdJoi9JnsG2nx/NcJ842MHNeYOkyVcDmcoX/+ASKeQp7yaNuy4R9M10bJdS
      1cO1+9WBTyVsmcNA9MbXdfL65i2M+UDBztdtPgmzPRq+Yx9CgbEW4gT0DxvQjuBH
      99YH8oalIap7mL/Jwrh/uTryA+U1H6LTZvrGkF/YrV8I0C1LZsDwuSyYYjj37Dsy
      YgB4Air0X0xN5rmP19joRRnuaO3bjT2Zq4tOeAoeWMS6zgXD73mpgbthgYZwhAgE
      aD36dsL3Eb0+52qi7DlTvxvc5Lq3AgMBAAGjQjBAMA4GA1UdDwEB/wQEAwICrDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRjPMAM4KSrbIHvqfIRAswgtv/3DzAN
      BgkqhkiG9w0BAQsFAAOCAQEAHGrfo2u+Y8xI5k4e/+9wJZtN8B9AO7XYVxkQ/XRT
      EGkug7fZ/ArRWpRfAvocU9aBeFqiV0Rg9+pqAb4GEQ+5mu6HC94VRMCZVffI6bZL
      ruIDv0O/ZKDxVsjFl0YSKWnI+/2ANiHKb09J4thhl75CE267Q4OXScsnToTm/IOF
      eLfy9wJCE+l5I/X/6Hi4b1c11hfFrobeWggKWZOtB6p6Ptmz95W9/sHGFs7z41kz
      tJ9f5fMFOCXOBmqUpuAmJwuZQ0OqnyGkkE1i1a7UEN2ntT2ya3S3lAOqc0EbEsrp
      sBthNGZt/GxCsozJMzRMK532d188U4krF5v92mC6QP3O/A==
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2024-08-10T16:43:28Z"
    name: kube-root-ca.crt
    namespace: default
    resourceVersion: "3879212864"
    uid: e1b1a8bf-e6fc-4807-b2f3-0acc4e93e6cb
kind: List
metadata:
  resourceVersion: ""
