apiVersion: v1
items:
- apiVersion: apps/v1
  data:
    spec:
      template:
        $patch: replace
        metadata:
          annotations:
            redeploy-timestamp: "1723315624138"
          creationTimestamp: null
          labels:
            app: etcd
        spec:
          containers:
          - args:
            - --name=$(POD_NAME)
            - --data-dir=/var/lib/etcd
            - --listen-client-urls=http://0.0.0.0:2379
            - --advertise-client-urls=http://$(POD_NAME).etcd.ws.svc.cluster.local:2379
            - --listen-peer-urls=http://0.0.0.0:2380
            - --initial-advertise-peer-urls=http://$(POD_NAME).etcd.ws.svc.cluster.local:2380
            - '--initial-cluster=etcd-0=http://etcd-0.etcd.ws.svc.cluster.local:2380,etcd-1=http://etcd-1.etcd.ws.svc.cluster.local:2380  #
              只保留两个节点'
            - --initial-cluster-state=new
            command:
            - /usr/local/bin/etcd
            env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            image: registry-vpc.cn-shenzhen.aliyuncs.com/morpingsss/etcd:3.5.4
            imagePullPolicy: IfNotPresent
            name: etcd
            ports:
            - containerPort: 2379
              name: client
              protocol: TCP
            - containerPort: 2380
              name: peer
              protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /var/lib/etcd
              name: disk-ssd
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  kind: ControllerRevision
  metadata:
    creationTimestamp: "2024-08-10T18:47:04Z"
    labels:
      app: etcd
      controller.kubernetes.io/hash: 59c499d9b7
    name: etcd-59c499d9b7
    namespace: ws
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: StatefulSet
      name: etcd
      uid: 8ab18da5-5949-42c4-a2a4-5e111016681e
    resourceVersion: "3879541868"
    uid: 1e898619-66ae-4220-935c-f6a16cc7ad3d
  revision: 2
- apiVersion: apps/v1
  data:
    spec:
      template:
        $patch: replace
        metadata:
          creationTimestamp: null
          labels:
            app: etcd
        spec:
          containers:
          - args:
            - --name=$(POD_NAME)
            - --data-dir=/var/lib/etcd
            - --listen-client-urls=http://0.0.0.0:2379
            - --advertise-client-urls=http://$(POD_NAME).etcd.ws.svc.cluster.local:2379
            - --listen-peer-urls=http://0.0.0.0:2380
            - --initial-advertise-peer-urls=http://$(POD_NAME).etcd.ws.svc.cluster.local:2380
            - '--initial-cluster=etcd-0=http://etcd-0.etcd.ws.svc.cluster.local:2380,etcd-1=http://etcd-1.etcd.ws.svc.cluster.local:2380  #
              只保留两个节点'
            - --initial-cluster-state=new
            command:
            - /usr/local/bin/etcd
            env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            image: registry-vpc.cn-shenzhen.aliyuncs.com/morpingsss/etcd:3.5.4
            imagePullPolicy: IfNotPresent
            name: etcd
            ports:
            - containerPort: 2379
              name: client
              protocol: TCP
            - containerPort: 2380
              name: peer
              protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /var/lib/etcd
              name: disk-ssd
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  kind: ControllerRevision
  metadata:
    creationTimestamp: "2024-08-10T18:25:02Z"
    labels:
      app: etcd
      controller.kubernetes.io/hash: 66c94c64d8
    name: etcd-66c94c64d8
    namespace: ws
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: StatefulSet
      name: etcd
      uid: 8ab18da5-5949-42c4-a2a4-5e111016681e
    resourceVersion: "3879482763"
    uid: 43aeb452-8375-4492-8620-c0975642e92f
  revision: 1
- apiVersion: apps/v1
  data:
    spec:
      template:
        $patch: replace
        metadata:
          creationTimestamp: null
          labels:
            app: etcd
        spec:
          containers:
          - args:
            - --name=$(POD_NAME)
            - --data-dir=/var/lib/etcd
            - --listen-client-urls=http://0.0.0.0:2379
            - --advertise-client-urls=http://$(POD_NAME).etcd.ws.svc.cluster.local:2379
            - --listen-peer-urls=http://0.0.0.0:2380
            - --initial-advertise-peer-urls=http://$(POD_NAME).etcd.ws.svc.cluster.local:2380
            - --initial-cluster=etcd-0=http://etcd-0.etcd.ws.svc.cluster.local:2380,etcd-1=http://etcd-1.etcd.ws.svc.cluster.local:2380
            - --initial-cluster-state=new
            command:
            - /usr/local/bin/etcd
            env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            image: registry-vpc.cn-shenzhen.aliyuncs.com/morpingsss/etcd:3.5.4
            imagePullPolicy: IfNotPresent
            name: etcd
            ports:
            - containerPort: 2379
              name: client
              protocol: TCP
            - containerPort: 2380
              name: peer
              protocol: TCP
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /var/lib/etcd
              name: disk-ssd
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  kind: ControllerRevision
  metadata:
    creationTimestamp: "2024-08-20T01:13:51Z"
    labels:
      app: etcd
      controller.kubernetes.io/hash: 7464b764f8
    name: etcd-7464b764f8
    namespace: ws
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: StatefulSet
      name: etcd
      uid: 8ab18da5-5949-42c4-a2a4-5e111016681e
    resourceVersion: "3915384369"
    uid: 0b70bb00-e60b-498c-8909-4727765d0974
  revision: 4
- apiVersion: apps/v1
  data:
    spec:
      template:
        $patch: replace
        metadata:
          creationTimestamp: null
          labels:
            app: etcd
        spec:
          containers:
          - args:
            - --name=$(POD_NAME)
            - --data-dir=/var/lib/etcd
            - --listen-client-urls=http://0.0.0.0:2379
            - --advertise-client-urls=http://$(POD_NAME).etcd.ws.svc.cluster.local:2379
            - --listen-peer-urls=http://0.0.0.0:2380
            - --initial-advertise-peer-urls=http://$(POD_NAME).etcd.ws.svc.cluster.local:2380
            - --initial-cluster=etcd-0=http://etcd-0.etcd.ws.svc.cluster.local:2380,etcd-1=http://etcd-1.etcd.ws.svc.cluster.local:2380
            - --initial-cluster-state=new
            command:
            - /usr/local/bin/etcd
            env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            image: registry-vpc.cn-shenzhen.aliyuncs.com/morpingsss/etcd:3.5.4
            imagePullPolicy: IfNotPresent
            name: etcd
            ports:
            - containerPort: 2379
              name: client
              protocol: TCP
            - containerPort: 2380
              name: peer
              protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /var/lib/etcd
              name: disk-ssd
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  kind: ControllerRevision
  metadata:
    creationTimestamp: "2024-08-10T18:53:30Z"
    labels:
      app: etcd
      controller.kubernetes.io/hash: bb79ddddd
    name: etcd-bb79ddddd
    namespace: ws
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: StatefulSet
      name: etcd
      uid: 8ab18da5-5949-42c4-a2a4-5e111016681e
    resourceVersion: "3879559218"
    uid: 3671dd80-c6e2-4698-8c5a-90cfef975f45
  revision: 3
kind: List
metadata:
  resourceVersion: ""
